apiVersion: v1
kind: Service

metadata:
  name: college-event-service
  namespace: college-event

spec:

  selector:
    app: college-event

  type: NodePort

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080